name: scrape-and-update
on:
  schedule:
    - cron:  '25 2 * * *'   # 每天 UTC 02:25 ≈ 北京 10:25
  workflow_dispatch:        # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas
          playwright install chromium

      - name: Scrape
        run: python scrape_papers.py

      - name: Commit data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "chore: update data $(date +'%F')" || echo "no changes"
          git push
